from __future__ import annotations

import socket
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: python3 crash_once_server.py <host> <port> <dump_path>",
            file=sys.stderr,
        )
        return 2

    host = sys.argv[1]
    port = int(sys.argv[2])
    dump_path = Path(sys.argv[3]).resolve()
    dump_path.parent.mkdir(parents=True, exist_ok=True)

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as server:
        server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        server.bind((host, port))
        server.listen(1)
        conn, _ = server.accept()
        conn.close()

    dump_path.write_text("fake core dump generated by crash_once_server\n", encoding="utf-8")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
